spring:
 datasource:
    url: jdbc:sqlserver://localhost;database=springbootdb
    username: sa
    password: acehood21
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
 jpa:
    show-sql: true
    hibernate:
       dialect: org.hibernate.dialect.SQLServer2012Dialect
       ddl-auto: create-drop
    properties:
       hibernate:
          format_sql: true
 thymeleaf:  
  cache: false
 security:
  oauth2:
   client:
    registration:
     google:
      clientId: clientId
      clientSecret: clientsecret
     scope:
      - email
      - profile


okta:  
 oauth2:  
  issuer: https://dev-81312481.okta.com/oauth2/default  
  clientId: clientid
  clientSecret: clientSecret   
 
